import type { Metadata } from "next";
import { Providers } from "./providers";
import {Zen_Dots} from "next/font/google"
import "./globals.css";
import Header from "../components/header/Header";


const zenDots = Zen_Dots({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zenDots.className} antialiased`}
      >
        {" "}
        <div className="w-screen h-full overflow-scroll">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
